eureka:
  client:
    register-with-eureka: false
server:
  port: 9999
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bill
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/bill/**
        - id: customer
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/customer/**
        - id: inventory
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/inventory/**

